(() => {
  if(document.getElementById('n8nmeter-row-ui'))return;
  const host=document.createElement('div');host.id='n8nmeter-row-ui';host.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:2147483100';
  const root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>
  *{box-sizing:border-box}#popover{pointer-events:auto;position:fixed;width:310px;max-width:calc(100vw - 20px);max-height:calc(100vh - 20px);overflow:auto;background:var(--color--background--light-2,#252525);color:var(--color--text,#ededed);border:1px solid var(--color--foreground--tint-1,#484848);border-radius:11px;box-shadow:0 10px 34px #0005;padding:18px;font:12px system-ui}header{display:flex;align-items:center;justify-content:space-between;font-size:10px;color:var(--color--text--tint-1,#aaa)}header b{color:#ff985e;letter-spacing:.6px}button{font:inherit;cursor:pointer}#close{border:0;background:none;color:inherit;font-size:20px;padding:0 4px}h2{font-size:13px;font-weight:550;line-height:1.6;margin:13px 0 18px;overflow-wrap:anywhere}.label{font-size:11px;color:var(--color--text--tint-1,#aaa)}#root{font-size:33px;letter-spacing:-1px;font-weight:500;margin:4px 0 15px}.metrics{display:flex;gap:18px;border-top:1px solid #8883;padding-top:13px}.metrics div{flex:1}.metrics strong{display:block;font-size:17px;font-weight:500;margin-top:5px}.note{font-size:10px;line-height:1.8;color:var(--color--text--tint-1,#aaa);margin:14px 0 0}#status{color:#d69965;margin-top:12px;line-height:1.7;font-size:11px}details{margin-top:14px;border-top:1px solid #8883;padding-top:12px}summary{font-size:11px;cursor:pointer;color:#db9b71}details p{font-size:10px;color:var(--color--text--tint-1,#aaa);line-height:1.8}#refresh{margin-top:12px;background:none;border:1px solid #8884;color:inherit;border-radius:5px;padding:7px 10px;font-size:10px}button:focus-visible,summary:focus-visible{outline:2px solid #ff985e;outline-offset:3px}[hidden]{display:none!important}
  </style><section id="popover" role="dialog" aria-label="워크플로 사용량" hidden><header><b>N8N_METER</b><span>워크플로 사용량</span><button id="close" aria-label="사용량 닫기">×</button></header><h2 id="name"></h2><div class="label">라이선스 전송 · 루트 실행 누적</div><div id="root">—</div><div class="metrics"><div><span class="label">전체 프로덕션</span><strong id="production">—</strong></div><div><span class="label">실패한 루트 실행</span><strong id="failed">—</strong></div></div><p id="status" role="status"></p><p class="note" id="at"></p><details><summary>어떤 실행이 집계되나요?</summary><p>n8n 2.26.9의 라이선스 전송 원천 통계입니다. 성공·실패와 Error Workflow도 rootCount에 포함되며, 수동 실행과 서브워크플로는 루트 통계에서 제외됩니다. 최종 과금값을 확정하는 지표는 아닙니다.</p><p>설치 전 월별 이력은 복원하지 않습니다. 이 팝오버는 워크플로별 누적값만 표시합니다.</p></details><button id="refresh">↻ 새로고침</button></section>`;
  document.documentElement.append(host);
  const style=document.createElement('style');style.id='n8nmeter-row-style';style.textContent=`[data-n8nmeter-card] .n8nmeter-usage-button{font:11px system-ui;color:var(--color--text--tint-1,#aaa);background:transparent;border:1px solid var(--color--foreground--tint-1,#555);border-radius:5px;padding:5px 8px;white-space:nowrap;cursor:pointer;opacity:1;pointer-events:auto}[data-n8nmeter-card] .n8nmeter-usage-button:hover{color:#e89763;border-color:#a66e4b}[data-n8nmeter-card] .n8nmeter-usage-button:focus-visible{outline:2px solid #ff985e;outline-offset:2px}`;
  document.head.append(style);
  const $=id=>root.getElementById(id), num=v=>v==null?'—':BigInt(v).toLocaleString('ko-KR');
  let active=null, generation=0, scheduled=false;
  function close(restore=false){generation++;$('popover').hidden=true;if(active){active.button.setAttribute('aria-expanded','false');if(restore&&active.button.isConnected)active.button.focus();}active=null;}
  function position(){if(!active)return;if(!active.button.isConnected||active.card.dataset.n8nmeterWorkflowId!==active.id){close();return;}const b=active.button.getBoundingClientRect();if(b.bottom<0||b.top>innerHeight){close();return;}const p=$('popover'),w=p.offsetWidth,h=p.offsetHeight;p.style.left=Math.max(10,Math.min(innerWidth-w-10,b.right-w))+'px';p.style.top=Math.max(10,b.bottom+h+8<innerHeight?b.bottom+8:b.top-h-8)+'px';}
  async function load(){if(!active)return;const turn=++generation, id=active.id;$('root').textContent='—';$('production').textContent='—';$('failed').textContent='—';$('at').textContent='';$('status').textContent='통계를 확인하고 있습니다.';
    if(!id){$('status').textContent='워크플로 ID 연결을 확인하지 못했습니다. 페이지를 새로고침해 주세요. 사용량을 0회로 표시하지 않습니다.';position();return;}
    try{let data;if(typeof chrome!=='undefined'&&chrome.runtime?.id){const r=await chrome.runtime.sendMessage({type:'n8nmeter:summary'});if(r?.error)throw new Error(r.error);data=r?.data;}else{const r=await fetch('/__n8nmeter/api/summary',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('수집기 연결을 확인해 주세요.');data=await r.json();}if(turn!==generation)return;if(data?.product!=='n8n Meter')throw new Error('수집기 응답을 확인할 수 없습니다.');const item=data.workflows.find(w=>w.id===id);
      if(item){$('root').textContent=num(item.root);$('production').textContent=num(item.production);$('failed').textContent=num(item.failed);$('status').textContent=data.mode==='snapshot'?'DB 스냅샷 · 자동 수집 연결 전':data.error||data.stale?'수집 확인 필요 · 마지막 성공값':!data.verifiedAdapter?'이 버전의 집계 규칙은 미검증입니다.':'라이선스 전송 원천값 · 최종 과금값 아님';}
      else $('status').textContent='이 ID에 연결된 통계가 없습니다. 0회로 판단하지 않습니다. 수집 대상·보존 범위·상위 100개 제한을 확인해 주세요.';
      $('at').textContent='수집: '+(data.last?new Date(data.last.at).toLocaleString('ko-KR'):'없음');position();
    }catch(e){if(turn===generation){$('status').textContent=e.message;position();}}
  }
  function open(card,button){const id=card.dataset.n8nmeterWorkflowId;if(active?.button===button){close();return;}close();active={card,button,id};button.setAttribute('aria-expanded','true');$('name').textContent=card.querySelector('[data-test-id="workflow-card-name"]')?.textContent.trim()||id;$('popover').hidden=false;root.querySelector('details').open=false;position();$('close').focus();load();}
  function scan(){scheduled=false;for(const menu of document.querySelectorAll('[data-test-id="workflow-card-actions"]')){const card=menu.closest('.card, [data-test-id="workflow-card"]');if(card&&!card.hasAttribute('data-n8nmeter-card'))card.setAttribute('data-n8nmeter-card','');}for(const card of document.querySelectorAll('[data-n8nmeter-card]')){const id=card.dataset.n8nmeterWorkflowId,old=card.querySelector('.n8nmeter-usage-button');const menu=card.querySelector('[data-test-id="workflow-card-actions"]');if(!menu?.parentElement)continue;if(old)continue;const button=document.createElement('button');button.type='button';button.className='n8nmeter-usage-button';button.textContent='◈ 사용량';button.setAttribute('aria-label','워크플로 사용량 보기');button.setAttribute('aria-expanded','false');button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(card,button);});button.addEventListener('pointerdown',e=>e.stopPropagation());menu.parentElement.insertBefore(button,menu);}position();}
  const observer=new MutationObserver(()=>{if(!scheduled){scheduled=true;requestAnimationFrame(scan);}});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['data-n8nmeter-workflow-id']});scan();
  $('close').onclick=()=>close(true);$('refresh').onclick=load;
  document.addEventListener('pointerdown',e=>{if(active&&!e.composedPath().includes(host)&&!e.composedPath().includes(active.button))close();},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active){e.stopPropagation();close(true);}},true);
  document.addEventListener('scroll',position,true);window.addEventListener('resize',position);
})();
